services:
  turnitin-slayer:
    build:
      context: .
      dockerfile: Dockerfile
    image: turnitin-slayer:latest
    container_name: turnitin-slayer-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # Hapus komentar di bawah ini HANYA JIKA sedang development (hot reload)
    #   - ./src:/app/src
